import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { X, Copy, Check, FileText, Download } from "lucide-react";

export default function SummaryModal({ open, onClose, summary }) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setCopied(false);
  }, [open]);

  useEffect(() => {
    const handleEsc = (e) => {
      if (e.key === "Escape") onClose();
    };
    if (open) {
      document.body.style.overflow = "hidden";
      window.addEventListener("keydown", handleEsc);
    }
    return () => {
      document.body.style.overflow = "unset";
      window.removeEventListener("keydown", handleEsc);
    };
  }, [open, onClose]);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([summary], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "summary.md";
    document.body.appendChild(element);
    element.click();
  };

  return (
    <AnimatePresence>
      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 backdrop-blur-sm"
            style={{ background: 'rgba(0,0,0,0.5)' }}
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ duration: 0.25 }}
            className="w-full max-w-3xl max-h-[80vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden relative"
            style={{
              background: 'var(--bg-card)',
              border: '1px solid var(--border-color)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-6 py-4 flex-shrink-0"
              style={{ borderBottom: '1px solid var(--border-light)', background: 'var(--bg-surface)' }}
            >
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg" style={{ background: 'rgba(139,92,246,0.15)', color: '#a78bfa' }}>
                  <FileText size={20} />
                </div>
                <div>
                  <h2 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>Study Summary</h2>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Generated by AI Tutor</p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button onClick={handleCopy} className="p-2 rounded-lg transition-all"
                  style={{ color: 'var(--text-muted)' }} title="Copy Text"
                >
                  {copied ? <Check size={20} style={{ color: 'var(--success-text)' }} /> : <Copy size={20} />}
                </button>
                <button onClick={handleDownload} className="p-2 rounded-lg transition-all"
                  style={{ color: 'var(--text-muted)' }} title="Download MD"
                >
                  <Download size={20} />
                </button>
                <div className="w-px h-6 mx-1" style={{ background: 'var(--border-color)' }} />
                <button onClick={onClose} className="p-2 rounded-lg transition-all"
                  style={{ color: 'var(--text-muted)' }}
                >
                  <X size={22} />
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 md:p-8 custom-scrollbar w-full"
              style={{ background: 'var(--bg-card)' }}
            >
              <article
                className="prose max-w-none w-full break-words"
                style={{ color: 'var(--text-primary)' }}
              >
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    table: ({ node, ...props }) => (
                      <div className="block w-full overflow-x-auto my-6 rounded-lg shadow-sm"
                        style={{ border: '1px solid var(--border-color)' }}
                      >
                        <table className="min-w-full divide-y text-sm" style={{ borderColor: 'var(--border-color)' }} {...props} />
                      </div>
                    ),
                    thead: ({ node, ...props }) => (
                      <thead style={{ background: 'var(--bg-surface)' }} {...props} />
                    ),
                    tbody: ({ node, ...props }) => (
                      <tbody className="divide-y" style={{ borderColor: 'var(--border-color)' }} {...props} />
                    ),
                    tr: ({ node, ...props }) => (
                      <tr className="transition-colors" {...props} />
                    ),
                    th: ({ node, ...props }) => (
                      <th className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wider whitespace-nowrap"
                        style={{ color: 'var(--text-muted)' }} {...props}
                      />
                    ),
                    td: ({ node, ...props }) => (
                      <td className="px-4 py-3 whitespace-normal align-top leading-relaxed"
                        style={{ color: 'var(--text-secondary)' }} {...props}
                      />
                    ),
                    h1: ({ node, ...props }) => (
                      <h1 className="text-2xl font-bold mt-6 mb-3" style={{ color: 'var(--text-primary)' }} {...props} />
                    ),
                    h2: ({ node, ...props }) => (
                      <h2 className="text-xl font-bold mt-5 mb-2" style={{ color: 'var(--text-primary)' }} {...props} />
                    ),
                    h3: ({ node, ...props }) => (
                      <h3 className="text-lg font-bold mt-4 mb-2" style={{ color: 'var(--text-primary)' }} {...props} />
                    ),
                    p: ({ node, ...props }) => (
                      <p className="mb-3 leading-relaxed" style={{ color: 'var(--text-secondary)' }} {...props} />
                    ),
                    li: ({ node, ...props }) => (
                      <li className="mb-1" style={{ color: 'var(--text-secondary)' }} {...props} />
                    ),
                    code: ({ node, inline, ...props }) =>
                      inline ? (
                        <code className="px-1.5 py-0.5 rounded text-sm"
                          style={{ background: 'var(--bg-input)', color: 'var(--accent)' }} {...props}
                        />
                      ) : (
                        <code className="block p-4 rounded-xl text-sm overflow-x-auto my-4"
                          style={{ background: 'var(--bg-input)', color: 'var(--text-primary)' }} {...props}
                        />
                      ),
                  }}
                >
                  {summary}
                </ReactMarkdown>
              </article>
            </div>

            {/* Footer */}
            <div className="px-6 py-4 flex justify-end flex-shrink-0 rounded-b-2xl"
              style={{ borderTop: '1px solid var(--border-light)', background: 'var(--bg-surface)' }}
            >
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={onClose}
                className="px-6 py-2 text-white font-medium rounded-xl transition-colors shadow-lg"
                style={{ background: 'var(--accent)' }}
              >
                Close
              </motion.button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
