import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { X, Copy, Check, FileText, Download } from "lucide-react";

export default function SummaryModal({ open, onClose, summary }) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setCopied(false);
  }, [open]);

  // Handle Escape Key
  useEffect(() => {
    const handleEsc = (e) => {
      if (e.key === "Escape") onClose();
    };
    if (open) window.addEventListener("keydown", handleEsc);
    return () => window.removeEventListener("keydown", handleEsc);
  }, [open, onClose]);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([summary], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "summary.md";
    document.body.appendChild(element);
    element.click();
  };

  if (!open) return null;

  return (
    <div
      // UPDATED LINE: Changed to a subtle white semi-transparent background with a small blur
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-white/40 transition-all"
      onClick={onClose}
    >
      <div
        className="bg-white w-full max-w-3xl max-h-[80vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >

        {/* --- Header --- */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50/50 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-100 text-purple-600 rounded-lg">
              <FileText size={20} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-800">Study Summary</h2>
              <p className="text-xs text-slate-500">Generated by AI Tutor</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button onClick={handleCopy} className="p-2 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all" title="Copy Text">
              {copied ? <Check size={20} className="text-green-600" /> : <Copy size={20} />}
            </button>
            <button onClick={handleDownload} className="p-2 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all" title="Download MD">
              <Download size={20} />
            </button>
            <div className="w-px h-6 bg-slate-200 mx-1"></div>
            <button onClick={onClose} className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-all">
              <X size={22} />
            </button>
          </div>
        </div>

        {/* --- Scrollable Content --- */}
        <div className="flex-1 overflow-y-auto p-6 md:p-8 bg-white custom-scrollbar w-full">
          <article className="prose prose-slate max-w-none w-full break-words">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                table: ({node, ...props}) => (
                  <div className="block w-full overflow-x-auto my-6 border border-slate-200 rounded-lg shadow-sm">
                    <table className="min-w-full divide-y divide-slate-200 text-sm" {...props} />
                  </div>
                ),
                thead: ({node, ...props}) => (
                  <thead className="bg-slate-50" {...props} />
                ),
                tbody: ({node, ...props}) => (
                  <tbody className="divide-y divide-slate-200 bg-white" {...props} />
                ),
                tr: ({node, ...props}) => (
                  <tr className="hover:bg-slate-50/50 transition-colors" {...props} />
                ),
                th: ({node, ...props}) => (
                  <th className="px-4 py-3 text-left text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap" {...props} />
                ),
                td: ({node, ...props}) => (
                  <td className="px-4 py-3 text-slate-700 whitespace-normal align-top leading-relaxed" {...props} />
                ),
              }}
            >
              {summary}
            </ReactMarkdown>
          </article>
        </div>

        {/* --- Footer --- */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex justify-end flex-shrink-0 rounded-b-2xl">
          <button
            onClick={onClose}
            className="px-6 py-2 bg-slate-900 text-white font-medium rounded-xl hover:bg-slate-800 transition-colors shadow-lg shadow-slate-200"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
}
